"""Add cohort_id to User

Revision ID: 9ab58399d33d
Revises: 42f293ef9bfb
Create Date: 2025-07-22 09:19:07.336448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab58399d33d'
down_revision = '42f293ef9bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cohort_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
    'fk_users_cohort_id',
    'cohorts',
    ['cohort_id'],
    ['id']
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cohort_id')

    # ### end Alembic commands ###
